"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-06-28 23:56:56.840828
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('aiko_channel', sa.String(length=64), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('join_policy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aiko_channel')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('aiko_username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aiko_username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('memberships',
    sa.Column('channel_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('channel_id', sa.String(length=26), nullable=False),
    sa.Column('sender_user_id', sa.String(length=26), nullable=True),
    sa.Column('sender_kind', sa.String(length=16), nullable=False),
    sa.Column('sender_label', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reply_to', sa.String(length=26), nullable=True),
    sa.Column('client_msg_id', sa.String(length=64), nullable=True),
    sa.Column('aiko_origin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'client_msg_id', name='uq_channel_client_msg')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel_id'), ['channel_id'], unique=False)

    op.create_table('social_identities',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_sub', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_sub', name='uq_social_provider_sub')
    )
    with op.batch_alter_table('social_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_identities_user_id'), ['user_id'], unique=False)

    op.create_table('user_blocks',
    sa.Column('blocker_user_id', sa.String(length=26), nullable=False),
    sa.Column('blocked_user_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocker_user_id', 'blocked_user_id')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_user_id'), ['blocked_user_id'], unique=False)

    op.create_table('message_reports',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=26), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reporter_user_id', name='uq_report_message_reporter')
    )
    with op.batch_alter_table('message_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reports_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reports_message_id'))

    op.drop_table('message_reports')
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_user_id'))

    op.drop_table('user_blocks')
    with op.batch_alter_table('social_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_identities_user_id'))

    op.drop_table('social_identities')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_channel_id'))

    op.drop_table('messages')
    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_table('channels')
    # ### end Alembic commands ###
