"""role + join_policy CHECK constraints (#11)

Closed-set enforcement at the DB, beyond the API boundary: even a direct SQL
write that bypasses the service-layer clamp cannot store an out-of-set value.

HAND-WRITTEN, not autogenerated: alembic's ``compare_metadata`` does not detect
CHECK constraints on SQLite (the deploy dialect), so ``--autogenerate`` emits an
empty migration here. The constraint SQL is hardcoded (a migration is a
point-in-time record and must not import evolving model code).

SQLite cannot ``ALTER TABLE ... ADD CONSTRAINT``; ``batch_alter_table`` rebuilds
each table (create new + copy + swap) with the constraint applied — the first
real schema *evolution* on top of the alembic adoption (#14). The literals here
must stay in sync with the Role / JoinPolicy enums in domain/models.py.

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_CHECK = "role IN ('admin', 'member')"
_JOIN_POLICY_CHECK = "join_policy IN ('invite_only', 'open')"


def upgrade() -> None:
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_check_constraint("ck_memberships_role", _ROLE_CHECK)
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_check_constraint("ck_channels_join_policy", _JOIN_POLICY_CHECK)


def downgrade() -> None:
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_constraint("ck_channels_join_policy", type_="check")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_constraint("ck_memberships_role", type_="check")
