"""device_tokens table for push notifications (#16, increment 1)

Adds the push-notification roster: a user's registered APNs/FCM device tokens.
Increment 1 is storage + registration only; the actual sending (a hook in the
message fanout) is increment 2.

HAND-WRITTEN, not autogenerated (the convention adopted in #14): a migration is a
point-in-time record and must not import evolving model code, so the column
shapes and the platform CHECK literal are hardcoded here. They must stay in sync
with the DeviceToken model + Platform enum in domain/models.py.

A plain CREATE TABLE (no batch_alter_table): there is no existing table to
rebuild, and SQLite supports CHECK + UNIQUE inline in CREATE TABLE, so this needs
none of the table-rebuild dance 0002 used for an ALTER.

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Closed set of push platforms — must match the Platform StrEnum in models.py.
_PLATFORM_CHECK = "platform IN ('apns', 'fcm')"


def upgrade() -> None:
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("platform", sa.String(length=8), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.UniqueConstraint("token", name="uq_device_tokens_token"),
        sa.CheckConstraint(_PLATFORM_CHECK, name="ck_device_tokens_platform"),
    )
    op.create_index(
        "ix_device_tokens_user_id", "device_tokens", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_device_tokens_user_id", table_name="device_tokens")
    op.drop_table("device_tokens")
