"""oauth_handoffs table for the server-side OAuth broker (#21)

Adds the one-time handoff store the broker callback writes and the
/v1/auth/oauth/exchange endpoint redeems. The broker completes the
authorization-code exchange server-side and must NOT put minted tokens in a
redirect URL, so it stashes a minimal outcome payload here under a random
single-use code and hands the browser only that opaque code.

HAND-WRITTEN, not autogenerated (the convention adopted in #14): a migration is a
point-in-time record and must not import evolving model code, so the column
shapes are hardcoded here. They must stay in sync with the OAuthHandoff model in
domain/models.py.

A plain CREATE TABLE (no batch_alter_table): there is no existing table to
rebuild.

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "oauth_handoffs",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )


def downgrade() -> None:
    op.drop_table("oauth_handoffs")
