"""oauth_states table for the server-side OAuth broker (#21, cage-match #30)

Adds the one-time CSRF/PKCE state nonce store the broker /start writes and the
/callback consumes. Replaces the earlier self-contained signed-JWT ``state``
(Finding 1): the PKCE ``code_verifier`` now lives server-side in this row and the
nonce is single-use, so a captured callback can't be replayed at the state layer
and the verifier never crosses the wire.

HAND-WRITTEN, not autogenerated (the convention adopted in #14): a migration is a
point-in-time record and must not import evolving model code, so the column
shapes are hardcoded here. They must stay in sync with the OAuthState model in
domain/models.py.

A plain CREATE TABLE (no batch_alter_table): there is no existing table to
rebuild.

Revision ID: 0005
Revises: 0004
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "oauth_states",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("code_verifier", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("nonce"),
    )


def downgrade() -> None:
    op.drop_table("oauth_states")
