"""social_nonces table — server-issued single-use nonce (#13, option a)

Adds the store that makes the native sign-in nonce INDEPENDENT SERVER STATE: the
gateway issues a nonce (POST /v1/auth/nonce), stores it here, and consumes it
exactly once at /v1/auth/social. This closes the replay window PR#32's option (b)
left open (an app-supplied nonce travels with the token and is replayable).

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a point-in-
time record and must not import evolving model code. The column shapes must stay
in sync with the SocialNonce model in domain/models.py.

A plain CREATE TABLE — no batch_alter_table (no existing table to rebuild).

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "social_nonces",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("nonce"),
    )


def downgrade() -> None:
    op.drop_table("social_nonces")
