"""app_challenge column on oauth_states (app-bound handoff, cage-match #37)

Adds the APP's S256 challenge to the broker state row. The app generates a
verifier, sends base64url(sha256(verifier)) here at /start; the /callback copies
it into the handoff, and /exchange requires the matching verifier. This binds the
handoff to the originating app so a handoff code intercepted via a hijacked
Android custom scheme cannot be redeemed (the verifier never leaves the app).

HAND-WRITTEN, not autogenerated (the convention from #14): a migration is a
point-in-time record and must not import evolving model code, so the column shape
is hardcoded here. It must stay in sync with the OAuthState model in
domain/models.py.

Nullable: existing in-flight rows (if any) predate the column; the broker treats
a row without a challenge as the legacy un-bound path. New flows always set it.

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "oauth_states",
        sa.Column("app_challenge", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("oauth_states", "app_challenge")
