"""passkey_credentials + passkey_challenges tables — WebAuthn passkeys (#1471)

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a point-in-
time record and must not import evolving model code, so the column shapes are
hardcoded here. They must stay in sync with the PasskeyCredential /
PasskeyChallenge models in domain/models.py.

passkey_credentials holds one row per registered authenticator keypair (PUBLIC
key only — the private key never leaves the device). passkey_challenges is the
single-use ceremony-challenge store (mirrors oauth_states): `state` is the opaque
handle the app round-trips, its decoded bytes are the WebAuthn challenge, and the
CHECK on `operation` pins a challenge to the ceremony that minted it.

Revision ID: 0008
Revises: 0007
Create Date: 2026-06-29
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "passkey_credentials",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("credential_id", sa.String(length=512), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False),
        sa.Column("transports", sa.Text(), nullable=True),
        sa.Column("aaguid", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", name="uq_passkey_credential_id"),
    )
    op.create_index(
        "ix_passkey_credentials_user_id", "passkey_credentials", ["user_id"])
    op.create_table(
        "passkey_challenges",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "operation IN ('register', 'authenticate')",
            name="ck_passkey_challenges_operation"),
        sa.PrimaryKeyConstraint("state"),
    )


def downgrade() -> None:
    op.drop_table("passkey_challenges")
    op.drop_index(
        "ix_passkey_credentials_user_id", table_name="passkey_credentials")
    op.drop_table("passkey_credentials")
