"""communities + community_memberships + channels.community_id (#32, Phase B1)

Option B (nested communities/servers) foundation. Invisible to clients: it adds
the Community model, a community-membership join, and a community_id on channels,
then SEEDS a single default community ("Aiko"), assigns every existing channel to
it, and AUTO-JOINS every existing user. Channels still render flat (the B2
discovery/join endpoints are a later revision) — the hierarchy just exists under
the hood.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a
point-in-time record and must not import evolving model code, so the column
shapes and the CHECK literals are hardcoded here. They must stay in sync with the
Community / CommunityMembership / Channel models + the Visibility / Category /
Role enums in domain/models.py, and `_DEFAULT_COMMUNITY_ID` must equal
`models.DEFAULT_COMMUNITY_ID`.

Key design points (see the models for the full rationale):
  * The default community has a FIXED, all-zero PK so `upsert_channel` can assign
    it without a lookup (no "which community?" race window).
  * channels.community_id is added NULLABLE, BACKFILLED to the default community
    for every existing row, THEN the partial CHECK (`kind='dm' OR community_id IS
    NOT NULL`) + FK are applied via batch rebuild — so the rebuild's row-copy
    never trips the new CHECK. DMs (near-term) stay community-less via that CHECK.
  * The channels rebuild MUST preserve the existing ck_channels_join_policy CHECK
    and the aiko_channel unique constraint; test_migrations asserts both survive.

FK-enforcement dependency (same as 0002): rebuilding `channels` (a parent of
memberships/messages) is safe because the gateway does NOT enable SQLite
`PRAGMA foreign_keys` — the parent-table swap cannot trip a child FK violation
mid-rebuild.

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-30
"""
from __future__ import annotations

import datetime as dt
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Point-in-time copies — MUST match domain/models.py (DEFAULT_COMMUNITY_ID and the
# Visibility / Category / Role StrEnums). The parity gate + the structural CHECK
# assertions in test_migrations catch drift.
_DEFAULT_COMMUNITY_ID = "0" * 26
_VISIBILITY_CHECK = "visibility IN ('public', 'unlisted', 'private')"
_CATEGORY_CHECK = (
    "category IN ('general', 'tech', 'gaming', 'social', 'music', "
    "'education', 'other')")
_ROLE_CHECK = "role IN ('admin', 'member')"
_COMMUNITY_REQUIRED_CHECK = "kind = 'dm' OR community_id IS NOT NULL"


def upgrade() -> None:
    # --- new tables --------------------------------------------------------- #
    op.create_table(
        "communities",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=26), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("taken_down_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.CheckConstraint(_VISIBILITY_CHECK, name="ck_communities_visibility"),
        sa.CheckConstraint(_CATEGORY_CHECK, name="ck_communities_category"),
    )
    op.create_index(
        "ix_communities_owner_id", "communities", ["owner_id"], unique=False)

    op.create_table(
        "community_memberships",
        sa.Column("community_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("community_id", "user_id"),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.CheckConstraint(_ROLE_CHECK, name="ck_community_memberships_role"),
    )

    # --- channels.community_id: add nullable, backfill, THEN constrain ------ #
    op.add_column(
        "channels", sa.Column("community_id", sa.String(length=26), nullable=True))
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE channels SET community_id = :cid"),
        {"cid": _DEFAULT_COMMUNITY_ID})

    # --- seed the default "Aiko" community + auto-join every existing user -- #
    now = dt.datetime.now(dt.timezone.utc)
    user_count = conn.execute(sa.text("SELECT COUNT(*) FROM users")).scalar() or 0
    # bulk_insert with typed lightweight tables so SQLAlchemy applies the DateTime
    # bind processor — a raw isoformat() string would not match the storage format
    # the ORM reads back.
    communities_tbl = sa.table(
        "communities",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("visibility", sa.String),
        sa.column("category", sa.String),
        sa.column("member_count", sa.Integer),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(communities_tbl, [{
        "id": _DEFAULT_COMMUNITY_ID,
        "name": "Aiko",
        "visibility": "public",
        "category": "general",
        "member_count": user_count,
        "created_at": now,
    }])

    user_ids = conn.execute(sa.text("SELECT id FROM users")).scalars().all()
    if user_ids:
        memberships_tbl = sa.table(
            "community_memberships",
            sa.column("community_id", sa.String),
            sa.column("user_id", sa.String),
            sa.column("role", sa.String),
            sa.column("joined_at", sa.DateTime(timezone=True)),
        )
        op.bulk_insert(memberships_tbl, [{
            "community_id": _DEFAULT_COMMUNITY_ID,
            "user_id": uid,
            "role": "member",
            "joined_at": now,
        } for uid in user_ids])

    # --- apply the FK + partial CHECK now that every row satisfies it ------- #
    # batch rebuild (SQLite can't ALTER ADD CONSTRAINT). The reflected table copy
    # carries the existing ck_channels_join_policy CHECK + the aiko_channel unique
    # constraint forward; test_migrations asserts both survive the rebuild.
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_channels_community_required", _COMMUNITY_REQUIRED_CHECK)
        batch_op.create_foreign_key(
            "fk_channels_community_id", "communities", ["community_id"], ["id"])

    # Index after the rebuild (the rebuild would otherwise reflect+recreate it).
    op.create_index(
        "ix_channels_community_id", "channels", ["community_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_channels_community_id", table_name="channels")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_constraint("fk_channels_community_id", type_="foreignkey")
        batch_op.drop_constraint("ck_channels_community_required", type_="check")
        batch_op.drop_column("community_id")
    op.drop_table("community_memberships")
    op.drop_index("ix_communities_owner_id", table_name="communities")
    op.drop_table("communities")
