"""communities.default_channel_id (#32, Phase B2)

Adds the `default_channel_id` column to `communities` — the channel a joiner lands
in / the directory highlights. It is a PLAIN String column, NOT a ForeignKey: a
real FK communities.default_channel_id -> channels.id together with the existing
channels.community_id -> communities.id forms a cycle SQLite's create_all (and a
batch rebuild) cannot order. Referential integrity is an application invariant (the
column is only ever set to a channel that belongs to the community); a dangling id
degrades gracefully app-side. This is the column deferred from B1's 0009 for
exactly that cycle reason.

Backfill: point the seeded "Aiko" community at its lowest-id channel as the default
landing channel. Prod has channels assigned to Aiko (0009), so this picks a stable
deterministic one; a community with no channels stays NULL.

HAND-WRITTEN, not autogenerated (the #14 convention). `_DEFAULT_COMMUNITY_ID` must
equal `models.DEFAULT_COMMUNITY_ID`.

Revision ID: 0010
Revises: 0009
Create Date: 2026-06-30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Point-in-time copy — MUST match domain/models.py DEFAULT_COMMUNITY_ID.
_DEFAULT_COMMUNITY_ID = "0" * 26


def upgrade() -> None:
    op.add_column(
        "communities",
        sa.Column("default_channel_id", sa.String(length=26), nullable=True),
    )
    conn = op.get_bind()
    # Pick the lowest-id channel assigned to the default community as its landing
    # channel. Deterministic (ORDER BY id) so a re-run / a fresh build agree.
    channel_id = conn.execute(
        sa.text(
            "SELECT id FROM channels WHERE community_id = :cid "
            "ORDER BY id LIMIT 1"
        ),
        {"cid": _DEFAULT_COMMUNITY_ID},
    ).scalar()
    if channel_id is not None:
        conn.execute(
            sa.text(
                "UPDATE communities SET default_channel_id = :ch WHERE id = :cid"
            ),
            {"ch": channel_id, "cid": _DEFAULT_COMMUNITY_ID},
        )


def downgrade() -> None:
    op.drop_column("communities", "default_channel_id")
