"""messages.origin — sovereign-signing envelope carriage (#1816)

Adds a nullable JSON column `origin` to `messages`. It carries the client-supplied
signing envelope {v, alg, key_version, sender_pubkey, client_msg_id, signed_at_ms,
sig} VERBATIM after shape-validation at the WS trust boundary
(domain/signing.validate_origin). The gateway is a CARRIER, not a verifier — it
never checks the signature; it persists + echoes so a recipient can reconstruct
the signed bytes and verify. NULL for unsigned messages and all bus-born rows.

A plain additive nullable column — SQLite `ADD COLUMN` handles it directly (no
batch rebuild). SQLite stores JSON as TEXT; SQLAlchemy's JSON type serializes.

HAND-WRITTEN, not autogenerated (the #14 convention).

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-09
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("messages", sa.Column("origin", sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column("messages", "origin")
