"""signing_keys table — sovereign-signing pubkey->account binding (#1816 PR B)

Records the contemporaneous binding "authenticated account X used Ed25519 public
key K at send time" — the piece that elevates an echoed `origin` from
forgery-as-echo toward a real pubkey->account binding. Written through ONE mutator
(signing_keys_service.record_signing_key), both implicitly (create_outbound, when
a signed message is sent) and explicitly (POST /v1/keys).

UNIQUE is (user_id, pubkey) — PER-USER, not global. The gateway is a carrier, not
a verifier; it knows "this account presented this key", never "this key belongs to
this account", so the constraint dedupes the observation it can actually make. A
cross-user duplicate is a recorded signal for a future trust root, not a
write-time failure. See the SigningKey model docstring for the full reasoning.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a
point-in-time record and must not import evolving model code, so the column shapes
are hardcoded here. They must stay in sync with the SigningKey model in
domain/models.py (the parity gate test_migrations_match_models enforces it).

A plain CREATE TABLE (no batch_alter_table): there is no existing table to
rebuild, and SQLite supports UNIQUE inline in CREATE TABLE.

Revision ID: 0012
Revises: 0011
Create Date: 2026-07-10
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: Union[str, None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "signing_keys",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("pubkey", sa.String(length=128), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.UniqueConstraint("user_id", "pubkey", name="uq_signing_keys_user_pubkey"),
    )
    op.create_index(
        "ix_signing_keys_user_id", "signing_keys", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_signing_keys_user_id", table_name="signing_keys")
    op.drop_table("signing_keys")
