"""social recovery tables + passkey_challenges CHECK adds 'recover' (Design 05)

Three new tables for guardian-approval-quorum social recovery (Design 05 §8):

  * recovery_policies   — one k-of-n policy per user (UNIQUE user_id).
  * recovery_approvers  — the n registered approver PUBLIC keys; UNIQUE(user_id,
    approver_pubkey) enforces distinct guardians at the schema level.
  * pending_recovery    — an in-flight recovery in the time-locked veto window;
    UNIQUE(user_id) means one pending recovery per user, and the finalize path is a
    single guarded DELETE with the deadline folded into the WHERE (§7 fixes the C2
    TOCTOU). finalize_token_hash stores sha256(token), never the raw token.

Plus a CHECK rebuild: PasskeyOperation gained a RECOVER member (the recover/start
single-use server nonce is a PasskeyChallenge row pinned to operation='recover'), so
the passkey_challenges.operation CHECK must widen to include 'recover' or a recovery
nonce insert would violate the closed set. SQLite cannot ALTER a CHECK in place;
batch_alter_table rebuilds the table (create new + copy + swap) with the new
constraint — the same mechanism as 0002. Safe because the gateway runs FK-off (it
relies on application-level cascades), so the table swap can't trip a child FK.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a point-in-time
record and must not import evolving model code, so column shapes + the CHECK literal
are hardcoded here and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces the tables; the structural CHECK assertion in
test_migrations enforces the operation set).

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-11
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The widened closed set, in sync with the PasskeyOperation enum in domain/models.py.
_OPERATION_CHECK = "operation IN ('register', 'authenticate', 'recover')"
_OPERATION_CHECK_OLD = "operation IN ('register', 'authenticate')"


def upgrade() -> None:
    # 1. Widen the passkey_challenges.operation CHECK to admit 'recover'. Drop the
    #    old same-named CHECK first, then create the widened one, inside ONE batch
    #    rebuild (drop+add same name in one CREATE would collide otherwise).
    with op.batch_alter_table("passkey_challenges", schema=None) as batch_op:
        batch_op.drop_constraint("ck_passkey_challenges_operation", type_="check")
        batch_op.create_check_constraint(
            "ck_passkey_challenges_operation", _OPERATION_CHECK)

    # 2. recovery_policies — one k-of-n policy per user.
    op.create_table(
        "recovery_policies",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("threshold_k", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.UniqueConstraint("user_id", name="uq_recovery_policies_user"),
    )

    # 3. recovery_approvers — the n approver public keys; distinct per user.
    op.create_table(
        "recovery_approvers",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("approver_pubkey", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.UniqueConstraint(
            "user_id", "approver_pubkey", name="uq_recovery_approvers_user_pubkey"),
    )
    op.create_index(
        "ix_recovery_approvers_user_id", "recovery_approvers", ["user_id"],
        unique=False)

    # 4. pending_recovery — the in-flight veto-window row (one per user).
    op.create_table(
        "pending_recovery",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("staged_credential_id", sa.String(length=512), nullable=False),
        sa.Column("staged_public_key", sa.Text(), nullable=False),
        sa.Column("staged_sign_count", sa.BigInteger(), nullable=False),
        sa.Column("veto_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalize_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.UniqueConstraint("user_id", name="uq_pending_recovery_user"),
    )


def downgrade() -> None:
    op.drop_table("pending_recovery")
    op.drop_index(
        "ix_recovery_approvers_user_id", table_name="recovery_approvers")
    op.drop_table("recovery_approvers")
    op.drop_table("recovery_policies")
    with op.batch_alter_table("passkey_challenges", schema=None) as batch_op:
        batch_op.drop_constraint("ck_passkey_challenges_operation", type_="check")
        batch_op.create_check_constraint(
            "ck_passkey_challenges_operation", _OPERATION_CHECK_OLD)
