"""moderation act-on-report: users.banned_at + message_reports resolution (Piece B)

Adds the columns the moderator subsystem writes (#7):

  * users.banned_at — nullable timestamp; NULL = active, set = suspended FROM this
    island (per-island, reversible, forward-looking ban). Enforced at every auth
    ingress via users_service.is_banned; does NOT delete the row or past messages.
  * message_reports.resolved_by_user_id — nullable FK to users.id: WHO actioned the
    report. Nullable so a moderator's later account deletion can't cascade-destroy
    the report audit trail.
  * message_reports.resolution — nullable String(16) in a closed set
    {taken_down, dismissed}; NULL = still pending. A DB CHECK enforces the closed
    set. SQLite cannot ALTER a CHECK in place, so batch_alter_table rebuilds the
    table (create new + copy + swap) with the constraint — the same mechanism as
    0002/0013. Safe because the gateway runs FK-off (application-level cascades), so
    the swap can't trip a child FK.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a
point-in-time record and must not import evolving model code, so the column shapes
and the CHECK literal are hardcoded here and must stay in sync with
domain/models.py (the parity gate test_migrations_match_models enforces the
columns; the structural CHECK assertion in test_migrations enforces the set).

Revision ID: 0014
Revises: 0013
Create Date: 2026-07-27
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: Union[str, None] = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The closed set, in sync with the ReportResolution enum in domain/models.py.
_RESOLUTION_CHECK = "resolution IN ('taken_down', 'dismissed')"


def upgrade() -> None:
    # 1. users.banned_at — plain nullable column; SQLite adds nullable columns
    #    natively, no batch rebuild needed.
    op.add_column(
        "users",
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 2. message_reports: add the two resolution columns AND the CHECK in one batch
    #    rebuild. The CHECK forces the table recreate anyway, so folding the column
    #    adds into the same batch keeps it to a single swap and lets the FK on
    #    resolved_by_user_id land in the rebuilt CREATE TABLE.
    with op.batch_alter_table("message_reports", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resolved_by_user_id", sa.String(length=26), nullable=True))
        batch_op.add_column(
            sa.Column("resolution", sa.String(length=16), nullable=True))
        batch_op.create_foreign_key(
            "fk_message_reports_resolved_by_user_id",
            "users", ["resolved_by_user_id"], ["id"])
        batch_op.create_check_constraint(
            "ck_message_reports_resolution", _RESOLUTION_CHECK)


def downgrade() -> None:
    with op.batch_alter_table("message_reports", schema=None) as batch_op:
        batch_op.drop_constraint("ck_message_reports_resolution", type_="check")
        batch_op.drop_constraint(
            "fk_message_reports_resolved_by_user_id", type_="foreignkey")
        batch_op.drop_column("resolution")
        batch_op.drop_column("resolved_by_user_id")
    op.drop_column("users", "banned_at")
