"""users.token_generation — per-user session-revocation generation (#1914)

Adds the column the stateless-JWT revocation mechanism keys on:

  * users.token_generation — INTEGER NOT NULL DEFAULT 0. Every access/refresh token
    embeds the `gen` it was minted at; a token is honoured only while its gen equals
    this column. Bumping it (recovery finalize re-key) invalidates EVERY outstanding
    token for the user in one write — the revocation HS256 JWTs otherwise lack.
    Checked live at every auth ingress (get_current_user, refresh, WS handshake),
    exactly like banned_at / is_banned.

DEFAULT 0 is the un-revoked baseline and is also what a pre-#1914 token (no `gen`
claim) reads as — so applying this migration and deploying does NOT mass-logout any
live session: existing tokens (gen absent → 0) still match the new column's 0.

SQLite adds a NOT NULL column with a DEFAULT natively (existing rows take the
default), so no batch rebuild is needed — same as 0014's users.banned_at add.

HAND-WRITTEN, not autogenerated (the #14 convention): the column shape is hardcoded
here and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces it).

Revision ID: 0015
Revises: 0014
Create Date: 2026-07-27
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: Union[str, None] = "0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("token_generation", sa.Integer(), nullable=False,
                  server_default="0"),
    )


def downgrade() -> None:
    op.drop_column("users", "token_generation")
