"""message_retractions table — forward-ULID takedown retraction events (#7)

A takedown soft-deletes a message (``Message.deleted_at``), which mutates a row
BELOW a client's forward watermark (``get_history`` catch-up is ``id > after``,
strictly greater) — so a client that already synced the message never re-observes
the deletion. A *retraction* is a NEW row with its own higher ULID referencing the
taken-down message; it rides the existing forward paths (history catch-up + WS
fanout), reaching offline-then-reconnect AND live clients with one mechanism. See
the Retraction model docstring for the full reasoning.

Written in the SAME transaction as the soft-delete (moderation_service.
take_down_message): the retraction is the durable system of record, WS fanout is a
latency optimisation over it.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a
point-in-time record and must not import evolving model code, so the column shapes
are hardcoded here and must stay in sync with the Retraction model in
domain/models.py (the parity gate test_migrations_match_models enforces it).

A plain CREATE TABLE (no batch_alter_table): there is no existing table to rebuild.
Two indexes match the ORM exactly (parity gate): ``ix_message_retractions_target_msg_id``
(the ``index=True`` column, for the per-message dedup lookup + block join) and the
COMPOSITE ``ix_message_retractions_channel_id_id`` on ``(channel_id, id)`` (the
forward-catch-up access path), declared via the model's ``__table_args__``.

Revision ID: 0016
Revises: 0015
Create Date: 2026-07-28
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0016"
down_revision: Union[str, None] = "0015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "message_retractions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("target_msg_id", sa.String(length=26), nullable=False),
        sa.Column("channel_id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["target_msg_id"], ["messages.id"]),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"]),
    )
    op.create_index(
        "ix_message_retractions_target_msg_id",
        "message_retractions", ["target_msg_id"], unique=False)
    # Composite (channel_id, id) — matches the forward-catch-up access path
    # (`WHERE channel_id=? AND id > ? ORDER BY id`), not a channel_id-only index.
    op.create_index(
        "ix_message_retractions_channel_id_id",
        "message_retractions", ["channel_id", "id"], unique=False)


def downgrade() -> None:
    op.drop_index(
        "ix_message_retractions_channel_id_id", table_name="message_retractions")
    op.drop_index(
        "ix_message_retractions_target_msg_id", table_name="message_retractions")
    op.drop_table("message_retractions")
