"""users.handle_changed_at — timestamp of the last handle change (#2631)

Adds the column the handle-change COOLDOWN keys on:

  * users.handle_changed_at — TIMESTAMP NULL. Stamped (server clock) each time a
    user's handle (username) actually CHANGES via PATCH /v1/me. NULL = the handle
    has never been changed since account creation, so the first change is always
    allowed. The mutate path refuses a change while
    (now - handle_changed_at) < settings.handle_change_cooldown_seconds (429 +
    retry_after). display_name edits and no-op same-handle writes never touch it.

NULLABLE with no default: existing rows read NULL (never-changed) and are free to
change immediately — applying this migration grants no one a spurious cooldown.
Purely additive (a nullable column add), so it satisfies the additive-only
migration lint (task #11) on this lineage.

HAND-WRITTEN, not autogenerated (the #14 convention): the column shape is hardcoded
here and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces it).

Revision ID: 0017
Revises: 0016
Create Date: 2026-08-06
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017"
down_revision: Union[str, None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("handle_changed_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("users", "handle_changed_at")
