"""users.kind + agent_bindings — the OIDC agent-ingress (Citizenship H1)

Two additions for the general OIDC agent door (claude-tasks#2403):

  * users.kind — VARCHAR(16) NOT NULL DEFAULT 'human', with a CHECK
    ``kind IN ('human','agent')``. Every existing row is a human, so server_default
    'human' backfills them with no data touch; the deploy does NOT reclassify anyone.
    'agent' is set ONLY server-side by agents_service (the admin-gated OIDC binding),
    never from a request field — a human cannot self-promote.

    This is the FIRST named constraint on the `users` table, and SQLite cannot add a
    CHECK in place, so the add-column + add-CHECK run inside ONE ``batch_alter_table``
    (the create-new / copy / swap dance env.py enables with render_as_batch=True). The
    single-writer SQLite + single-migrator-per-deploy invariant (migrate.py) makes the
    table rebuild safe. compare_metadata is CHECK-blind on SQLite, so the parity gate
    cannot see this CHECK — test_migrations asserts it structurally in the DDL instead.

  * agent_bindings — the admin-created allowlist mapping a GitHub Actions workload
    (repository, ref, workflow_ref) → an aiko agent identity (user_id), plus the
    expected OIDC `aud`. UNIQUE(repository, ref, workflow_ref) so a workload resolves
    to exactly one agent. This is the trust root of the OIDC door: only a token whose
    SIGNATURE-verified claims hit a row here (and whose aud matches) mints a token.

HAND-WRITTEN, not autogenerated (the #14 convention): the shapes are hardcoded here
and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces it — modulo the CHECK-blind caveat above).

Revision ID: 0017
Revises: 0016
Create Date: 2026-07-30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017"
down_revision: Union[str, None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # users.kind + its closed-set CHECK. SQLite can't ALTER-ADD a CHECK in place, so
    # batch rebuilds the table with both changes at once. Existing rows take the
    # server_default 'human' during the copy — no human is reclassified.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", sa.String(length=16), nullable=False,
                      server_default="human"))
        batch_op.create_check_constraint(
            "ck_users_kind", "kind IN ('human', 'agent')")

    # agent_bindings — the admin-gated OIDC allowlist (repo/ref/workflow → agent).
    op.create_table(
        "agent_bindings",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("repository", sa.String(length=255), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=False),
        sa.Column("workflow_ref", sa.String(length=512), nullable=False),
        sa.Column("aud", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        # NOT NULL to match the ORM (Mapped[dt.datetime], non-Optional). The value is
        # supplied by the model's python-side default (_utcnow) on every insert; no
        # server_default is needed because every write goes through the ORM.
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository", "ref", "workflow_ref",
            name="uq_agent_bindings_repo_ref_workflow"),
    )
    op.create_index(
        "ix_agent_bindings_user_id", "agent_bindings", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_agent_bindings_user_id", table_name="agent_bindings")
    op.drop_table("agent_bindings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("ck_users_kind", type_="check")
        batch_op.drop_column("kind")
