"""message_reactions table — one user's SIGNED emoji reaction to one message (#2634)

The v2 social layer's reactions, rebuilt SIGNED + IDENTITY-BEARING (the reverted
first cut was anonymous+unsigned). STATE, not EVENT (contrast message_retractions,
0016): a reaction changes an aggregate that message_view recomputes on every history
read, so there is no forward-ULID event row — just this table, folded into the
serializer as a viewer-dependent reactions[] projection. See the MessageReaction
model docstring for the full state-not-event reasoning + the named offline-catch-up
tradeoff, and docs/crucible/sovereign-reaction-signing/SIGNING-SPEC.md for the
carriage/signing contract.

Composite PK (message_id, user_id, emoji) makes a repeat-react idempotent (one row
per (message, user, emoji)) — exactly the SIGNING-SPEC idempotency key
(user, target_msg_id, exact-emoji-bytes) — and its leading message_id covers the
aggregation read (`WHERE message_id IN (...) GROUP BY emoji`). A separate index on
user_id serves the account-deletion purge and the per-viewer `reacted_by_me` probe.

`origin` is the nullable sovereign-signing envelope (JSON) the gateway CARRIES (does
not verify), mirroring messages.origin — NULL for an unsigned/legacy reaction.

HAND-WRITTEN, not autogenerated (the #14 convention): a migration is a point-in-time
record and must not import evolving model code, so the column shapes are hardcoded
here and must stay in sync with the MessageReaction model in domain/models.py (the
parity gate test_migrations_match_models enforces it — named PK constraint +
ix_message_reactions_user_id index declared to match the ORM exactly).

A plain CREATE TABLE (no batch_alter_table): there is no existing table to rebuild.

Revision ID: 0018
Revises: 0017
Create Date: 2026-08-08
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018"
down_revision: Union[str, None] = "0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "message_reactions",
        sa.Column("message_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("emoji", sa.String(length=64), nullable=False),
        # Sovereign-signing envelope the gateway carries verbatim; NULL when unsigned.
        sa.Column("origin", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "message_id", "user_id", "emoji", name="pk_message_reactions"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )
    # user_id index — the account-deletion purge (`DELETE ... WHERE user_id=?`) and
    # the per-viewer `reacted_by_me` probe; the composite PK already covers
    # message_id-led reads, so no separate message_id index is needed.
    op.create_index(
        "ix_message_reactions_user_id",
        "message_reactions", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(
        "ix_message_reactions_user_id", table_name="message_reactions")
    op.drop_table("message_reactions")
