"""agent_bindings: immutable repository_id + repository_owner_id (Citizenship H1)

The OIDC agent door originally authorized on the (repository, ref, workflow_ref)
triple, keyed on the MUTABLE repository NAME. A repo can be renamed or transferred,
and its name later recycled by a DIFFERENT owner — so the name alone is not a safe
authorization root: a recycled slug could mint the old agent identity (cage-match
finding, PR #106).

This adds GitHub's IMMUTABLE numeric ids to every binding:

  * repository_id        — GitHub's stable numeric id for the repo (never reused).
  * repository_owner_id  — GitHub's stable numeric id for the owner.

Both are emitted as JSON strings in the OIDC token, so they are stored as VARCHAR.
The OIDC door now REQUIRES them to match the binding (the name only LOCATES the row;
the ids AUTHORIZE it) — see domain/agents_service.authenticate_agent_oidc.

Both columns are NOT NULL to match the ORM (domain/models.AgentBinding). The
`agent_bindings` table is BRAND NEW in 0017 and unpopulated in every environment (the
OIDC agent door has never shipped to prod), so there are NO rows to backfill and a
straight NOT NULL add is safe. Should any binding exist, it MUST be re-created after
this migration (the admin re-runs POST /v1/agents/bindings with the numeric ids) — an
old binding without ids can never satisfy the new required match anyway. Added inside a
single batch_alter_table (SQLite can't ALTER-ADD a constrained column in place; the
create-new/copy/swap dance env.py enables with render_as_batch=True).

HAND-WRITTEN, not autogenerated (the #14 convention): kept in sync with
domain/models.py, enforced by test_migrations_match_models.

Revision ID: 0018
Revises: 0017
Create Date: 2026-07-30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018"
down_revision: Union[str, None] = "0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL, no server_default: the table is empty (0017 just created it; the agent
    # door has never shipped), so the batch rebuild copies zero rows and the NOT NULL
    # constraint holds. Every future insert goes through the ORM, which requires both.
    with op.batch_alter_table("agent_bindings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("repository_id", sa.String(length=64), nullable=False))
        batch_op.add_column(
            sa.Column("repository_owner_id", sa.String(length=64), nullable=False))


def downgrade() -> None:
    with op.batch_alter_table("agent_bindings", schema=None) as batch_op:
        batch_op.drop_column("repository_owner_id")
        batch_op.drop_column("repository_id")
