"""messages.mentions — key-bound @-mention spans carried on a message (#2632)

Adds the column the v2 @-mention feature stores its spans in:

  * messages.mentions — JSON NULL. A list of discriminated-target spans
    ``[{target_type, target_id, offset, length}]`` the client sends on the WS
    ``send`` frame (validated for SHAPE + caps at the trust boundary in
    domain/mentions.validate_mentions, then CARRIED verbatim — the gateway is a
    carrier, not a resolver). ``target_id`` is the mentioned KEY/opaque id, never
    a home-qualified string (ADR-0004 in aiko_chat_app: mention targets key off
    the opaque identity); ``offset``/``length`` index ``body`` in the client's
    declared basis (UTF-16, per the app) and are round-tripped OPAQUELY — the
    gateway never re-derives that indexing basis.

NO server-side mention DIRECTORY endpoint ships with this (ADR-0004 "no central
directory" superseded the earlier cap-20 handoff lock): autocomplete sources from
the channel member roster (the enriched GET /channels/{id}/members), not a
/v1/mentions search surface.

NULLABLE with no default: existing rows read NULL (no mentions) and message_view
omits the key, exactly like ``origin`` — absent means "no mentions", never
"invalid". Purely additive (a nullable column add), so it satisfies the
additive-only migration lint (task #11) on this lineage.

HAND-WRITTEN, not autogenerated (the #14 convention): the column shape is
hardcoded here and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces it).

Revision ID: 0019
Revises: 0018
Create Date: 2026-08-09
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0019"
down_revision: Union[str, None] = "0018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "messages",
        sa.Column("mentions", sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("messages", "mentions")
