"""users.is_agent_admin — first-class DB-backed agent-provisioning role (#2403)

Replaces the env-allowlist stopgap (AGENT_BINDING_ADMIN_IDS) with a persisted
capability that the agent-binding gate reads:

  * users.is_agent_admin — BOOLEAN NOT NULL DEFAULT 0. Gates minting a production
    agent identity (POST /v1/agents/bindings, require_agent_binding_admin). A
    HIGHER-privilege act than content moderation, so it is its OWN capability and
    never reuses the moderator set. Granted/revoked at runtime by an existing
    agent-admin; the first admin is seeded at boot from AGENT_ADMIN_BOOTSTRAP_IDS.

DEFAULT 0 backfills every existing row as a non-admin — the migration preserves all
existing users and reclassifies none (fail-closed: an island with no seeded/granted
admin can provision no agents). SQLite adds a NOT NULL column with a DEFAULT natively
(existing rows take the default), so no batch rebuild is needed — same as 0015's
users.token_generation add.

HAND-WRITTEN, not autogenerated (the #14 convention): the column shape is hardcoded
here and must stay in sync with domain/models.py (the parity gate
test_migrations_match_models enforces it).

Revision ID: 0019
Revises: 0018
Create Date: 2026-07-30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0019"
down_revision: Union[str, None] = "0018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("is_agent_admin", sa.Boolean(), nullable=False,
                  server_default="0"),
    )


def downgrade() -> None:
    op.drop_column("users", "is_agent_admin")
