"""channels.kind CHECK constraint (#2633, cage-match PR#124)

Closed-set enforcement for the channel kind, beyond the API boundary. Since DMs,
``kind`` is SECURITY-relevant: the WS send path gates bus federation on
``kind != 'dm'`` (a DM never crosses the shared ChatServer — design 11 §Decision 3),
so an out-of-set kind stored by a direct SQL write or a buggy path could silently
bypass that gate. This CHECK makes an out-of-set kind unrepresentable at the DB, the
same closed-set-at-the-DB posture ck_channels_join_policy / ck_memberships_role already
give (#11). The cage-match (Carnot + Tesla) flagged the privacy gate resting on an
unenforced open string.

SAFE AGAINST LIVE DATA: the only channel-creation path in the codebase is
channels_service.upsert_channel, which writes kind='standard'; verified against live
prod (both islands) — every existing channel is 'standard', comfortably inside the set.
So the rebuild copies every existing row without a CHECK violation.

HAND-WRITTEN, not autogenerated: alembic's compare_metadata does not detect CHECK
constraints on SQLite (the deploy dialect), so --autogenerate emits an empty migration.
The literal must stay in sync with the ChannelKind enum in domain/models.py (the parity
gate test_migrations enforces that).

SQLite cannot ALTER TABLE ... ADD CONSTRAINT; batch_alter_table rebuilds the channels
table (create new + copy + swap) with the constraint applied. Same FK-safety note as
0002: rebuilding ``channels`` (a parent of memberships.channel_id) drops+recreates it,
which is safe because the gateway does NOT enable SQLite PRAGMA foreign_keys (it relies
on application-level explicit cascades — see db.py / accounts_service), so the
parent-table swap cannot trip a child FK violation mid-rebuild.

Revision ID: 0020
Revises: 0019
Create Date: 2026-08-10
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0020"
down_revision: Union[str, None] = "0019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("kind", ChannelKind) in domain/models.py exactly (parity gate).
# 'group' is deliberately NOT included — the group PR adds it with its matching
# community-exemption in one migration (cage-match PR#124 Tesla; see the ChannelKind
# docstring). Pre-permitting it here without that rule reopens the community footgun.
_KIND_CHECK = "kind IN ('standard', 'llm', 'robot', 'dm')"

# Bidirectional community-membership CHECK (cage-match PR#124 Carnot): tightens the
# original 0001 `kind = 'dm' OR community_id IS NOT NULL` so a DM must ALSO have a NULL
# community — closing the leak where a DM stored WITH a community surfaces in
# visible_channels_in_community. Safe vs live prod: all channels are 'standard' with a
# community (non-DM arm); no DM exists yet. Must match the model CheckConstraint exactly.
_COMMUNITY_CHECK_OLD = "kind = 'dm' OR community_id IS NOT NULL"
_COMMUNITY_CHECK_NEW = (
    "(kind = 'dm' AND community_id IS NULL) "
    "OR (kind != 'dm' AND community_id IS NOT NULL)")

# A DM must be private (cage-match PR#124 Carnot/Tesla) — is_private gates READ access,
# so a non-private DM would be world-readable. Safe vs live prod: all channels are
# 'standard' (kind != 'dm' arm passes regardless of is_private).
_DM_PRIVATE_CHECK = "kind != 'dm' OR is_private = 1"
# 'dm:' prefix ⟺ kind='dm', BIDIRECTIONAL + CASE-SENSITIVE (cage-match PR#124
# Carnot+Tesla): a DM must be dm:-prefixed AND the dm: namespace is totally reserved (no
# non-DM may wear it, at any writer). substr(...) not LIKE — SQLite LIKE case-folds ASCII
# ('DM:a:b' would pass) but the Python gate is case-sensitive, so LIKE would reopen the
# federation hole. Safe vs prod: all channels are 'standard' with non-dm: names.
_DM_PREFIX_CHECK = (
    "(kind = 'dm' AND substr(aiko_channel, 1, 3) = 'dm:') "
    "OR (kind != 'dm' AND substr(aiko_channel, 1, 3) <> 'dm:')")
# A DM must be invite_only — an open-policy DM would create a self_join existence oracle
# (cage-match PR#124 Tesla). Safe vs prod (all channels are standard/invite_only-agnostic
# under the kind!='dm' arm).
_DM_INVITE_ONLY_CHECK = "kind != 'dm' OR join_policy = 'invite_only'"


def upgrade() -> None:
    # One batch rebuild of `channels` applies all four constraint changes (add the kind
    # CHECK, tighten the community CHECK, add the DM-private + DM-prefix CHECKs) in a
    # single table copy.
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_check_constraint("ck_channels_kind", _KIND_CHECK)
        batch_op.drop_constraint("ck_channels_community_required", type_="check")
        batch_op.create_check_constraint(
            "ck_channels_community_required", _COMMUNITY_CHECK_NEW)
        batch_op.create_check_constraint("ck_channels_dm_private", _DM_PRIVATE_CHECK)
        batch_op.create_check_constraint("ck_channels_dm_prefix", _DM_PREFIX_CHECK)
        batch_op.create_check_constraint(
            "ck_channels_dm_invite_only", _DM_INVITE_ONLY_CHECK)


def downgrade() -> None:
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_constraint("ck_channels_dm_invite_only", type_="check")
        batch_op.drop_constraint("ck_channels_dm_prefix", type_="check")
        batch_op.drop_constraint("ck_channels_dm_private", type_="check")
        batch_op.drop_constraint("ck_channels_community_required", type_="check")
        batch_op.create_check_constraint(
            "ck_channels_community_required", _COMMUNITY_CHECK_OLD)
        batch_op.drop_constraint("ck_channels_kind", type_="check")
