"""users.kind — honest account kind, human|agent (#3096)

Gives an agent (a bot/robot/LLM actor) a FIRST-CLASS account kind rather than a
flag hung off a human's identity. Grounded on the app tab's ADR-0005 (the identity
graph), which decides bot cardinality = Model B: every bot gets its own Principal,
backed by a vouch bond from its creator's. Model A ("the bot shares my identity")
is rejected there because it "fails robots-first-class permanently".

WHY THE COLUMN EARNS ITS PLACE: before this, messages_service._kind_for returned
the literal "human" for ANY authenticated account, and otherwise derived the kind
from the CHANNEL ('llm'/'robot'). So sender_kind answered "where was this sent"
rather than "who sent it", and the first agent to hold a User row would have worn
a human badge on every message. The column is what lets that function tell the
truth. It carries NO trust claim — a 'verified' affordance is out of scope (H3).

SAFE AGAINST LIVE DATA: added with server_default 'human', so every existing row
backfills to the honest value (no agent account can exist before this migration)
and the NOT NULL is satisfiable in one step. The server_default is KEPT rather
than dropped after backfill: a direct SQL INSERT that omits the column should get
'human', not fail — the safe direction for a kind that gates how a sender is
rendered.

HAND-WRITTEN, not autogenerated: alembic's compare_metadata is CHECK-blind on
SQLite (the deploy dialect), so --autogenerate emits no constraint. The literal
must stay in sync with the UserKind enum in domain/models.py; tests/test_migrations
asserts ck_users_kind structurally in the migrated DDL for exactly that reason.

SQLite cannot ALTER TABLE ... ADD CONSTRAINT, so batch_alter_table rebuilds the
users table (create new + copy + swap) with the column and constraint applied.
FK-safety: rebuilding ``users`` (a parent of social_identities.user_id,
memberships.user_id and others) drops+recreates it, which is safe because the
gateway does NOT enable SQLite PRAGMA foreign_keys — it relies on application-level
explicit cascades (see db.py / accounts_service) — so the parent-table swap cannot
trip a child FK violation mid-rebuild. Same note as 0002 and 0020.

Revision ID: 0022
Revises: 0021
Create Date: 2026-08-15
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0022"
down_revision: Union[str, None] = "0021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("kind", UserKind) in domain/models.py exactly (parity gate).
_KIND_CHECK = "kind IN ('human', 'agent')"


def upgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", sa.String(length=16), nullable=False,
                      server_default="human"))
        batch_op.create_check_constraint("ck_users_kind", _KIND_CHECK)


def downgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("ck_users_kind", type_="check")
        batch_op.drop_column("kind")
