"""device_tokens.push_environment — which APNs world a token belongs to (#3386)

Apple runs two independent push services with non-interchangeable tokens. Before
this, the island answered "which one?" ONCE per box, from `APNS_USE_SANDBOX` —
so a gateway could ring debug builds or TestFlight builds, never both. The answer
is a property of the TOKEN (the `.p8` signing key is valid for both; the device
token is not), and this column is where it now lives.

WHY IT CANNOT BE INFERRED: `domain/apns.py` says it in the reaping rule — "a token
carries no marking that says which environment it belongs to; the two are
indistinguishable by inspection." The client declares it at registration; there is
no server-side derivation to fall back on.

BACKFILL IS SETTINGS-AWARE, THE DDL IS NOT. The column is added with a FIXED
server_default ('production', matching Settings.apns_use_sandbox's own default) so
the schema this migration produces is byte-identical on every island — the parity
gate diffs migrated DDL against models.py and must not depend on a box's .env.
The honest value for rows that already exist is a different question: they were
registered under whatever this island's global flag said, so a separate UPDATE
sets them to exactly that. Static DDL, dynamic data.

OPERATOR HAZARD, NAMED RATHER THAN GUARDED: the backfill reads the SAME process
environment the gateway does. Run inside the container (which is how `migrate.run`
fires at boot, and the only supported path) it sees the box's real
`APNS_USE_SANDBOX`. Run by hand on the host with a bare shell it would see the
Settings default (production) and stamp that onto rows a sandbox-pinned island
registered. That mis-stamp costs one refused push per device — a 400
BadDeviceToken, which the reaper deliberately does NOT act on — and is repaired by
a one-line UPDATE, so it does not earn a guard. It does earn this paragraph.

Both live islands hold ZERO device_tokens rows at authoring time (the app tab
deleted the last one on 2026-08-25 as a deliberate teardown-test arm), so the
UPDATE is expected to be a no-op in production today. It is written for
correctness, not for the rows we know about.

SQLite cannot ALTER TABLE ... ADD CONSTRAINT, so batch_alter_table rebuilds the
table (create new + copy + swap). FK-safety: `device_tokens` is a CHILD only
(user_id -> users.id) and no table references it, so the swap cannot orphan a
dependant; and the gateway does not enable SQLite PRAGMA foreign_keys anyway —
it uses application-level explicit cascades (see accounts_service). Same note as
0002 / 0020 / 0022.

HAND-WRITTEN, not autogenerated: alembic's compare_metadata is CHECK-blind on
SQLite (the deploy dialect), so --autogenerate emits no constraint. The literal
below must stay in sync with the PushEnvironment enum in domain/models.py;
tests/test_migrations asserts it structurally in the migrated DDL for that reason.

Revision ID: 0023
Revises: 0022
Create Date: 2026-08-25
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0023"
down_revision: Union[str, None] = "0022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("push_environment", PushEnvironment) in domain/models.py
# exactly (parity gate).
_ENV_CHECK = "push_environment IN ('sandbox', 'production')"


def upgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("push_environment", sa.String(length=16), nullable=False,
                      server_default="production"))
        batch_op.create_check_constraint(
            "ck_device_tokens_push_environment", _ENV_CHECK)

    # Imported HERE rather than at module scope: a migration that reads app config
    # at import time makes `alembic history` depend on a valid .env, and this value
    # is needed only while actually upgrading.
    from aiko_gateway.config import settings

    op.execute(
        sa.text("UPDATE device_tokens SET push_environment = :env").bindparams(
            env="sandbox" if settings.apns_use_sandbox else "production"))


def downgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_push_environment", type_="check")
        batch_op.drop_column("push_environment")
