"""device_tokens.push_environment -> apns_environment (#3386, Nick's ruling)

A NAME-ONLY reconciliation. No column is added or dropped, no value changes, no
row is touched: this migration exists so the deployed schema says what #3386's
body said it would say.

WHY IT IS A MIGRATION AND NOT AN EDIT. v0.8.0 shipped `push_environment` — built
from a later comment on #3386 rather than the issue body, which specified
`device_tokens.apns_environment` verbatim. The name that shipped was then defended
on its merits (Settings.environment collides on the literal 'production'), an
argument that is true but was made in ignorance of the recorded choice. The
collision argument survives and is why the column is not simply `environment`; it
was never a reason to prefer `push_` over `apns_`. Both live islands already ran
0023, so the reconciliation costs a revision.

`apns_` IS ALSO THE MORE HONEST HALF. The environment split is a property of APNs,
not of push: the `.p8` signing key is valid in both worlds, and FCM has no such
division — an 'fcm' row carries a value nothing reads. See the ApnsEnvironment
docstring in domain/models.py.

THE WIRE FIELD MOVES WITH THE COLUMN, so this is a BREAKING contract change, and
it is safe today for one reason that was measured rather than assumed: there is no
deployed consumer. MEASURED 2026-08-26, not a standing invariant — `git grep
push_environment origin/main -- '*.dart'` in aiko_chat_app returned zero, its
PR#162 was open and unmerged, and the last submitted IPA (0.0.3+11, 10 Aug) had no
aps-environment entitlement at all, so it could not hold an APNs token. The app tab
confirmed each of those independently before this was written. If you are reading
this while debugging a wire-compat bug, re-measure rather than inherit it.
That is why NO dual-key compatibility window was built: accepting both keys for a
release would be a mechanism for a state that cannot occur.

THE HAZARD IF THE TWO HALVES DESYNC IS SILENT, WHICH IS WHY THE ORDER IS FIXED.
The field is OPTIONAL on the wire: an unknown key is ignored and the row falls
back to the island's own default. So an app sending `push_environment` to an
island reading `apns_environment` registers with a 200, looks healthy, and then
fails every push to a release-build token with a 400 BadDeviceToken that no user
sees — re-creating, by naming alone, the exact failure #3386 exists to remove.
Agreed sequencing: the island merges and DEPLOYS first, then aiko_chat_app#162.
The app tab holds a live drift test that asserts set-equality against this
island's served /openapi.json; it goes RED the moment this deploys, which is what
it was built for.

SQLite CANNOT ALTER A CHECK, so batch_alter_table rebuilds the table (create new +
copy + swap), the same shape as 0023 / 0022 / 0020. The constraint is renamed with
the column — a constraint named for a column that no longer exists is a lie the
next reader has to unpick. FK-safety is unchanged from 0023: `device_tokens` is a
CHILD only (user_id -> users.id), nothing references it, so a swap cannot orphan a
dependant; and the gateway does not enable SQLite PRAGMA foreign_keys anyway
(ADR-0002, application-level cascades).

DATA SURVIVES THE REBUILD. batch mode copies by column, and a rename is declared
rather than inferred, so every existing row keeps its value — including
imagineering's one real production token, which 0023's settings-aware UPDATE
correctly stamped 'sandbox'. A rebuild that silently re-defaulted that row would
put a live handset back on the wrong host, so tests/test_migrations asserts the
value survives 0023 -> 0024 rather than trusting the copy.

HAND-WRITTEN, not autogenerated: alembic's compare_metadata is CHECK-blind on
SQLite (the deploy dialect), so --autogenerate emits no constraint. The literal
below must stay in sync with the ApnsEnvironment enum in domain/models.py;
tests/test_migrations asserts it structurally in the migrated DDL for that reason.

Revision ID: 0024
Revises: 0023
Create Date: 2026-08-26
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0024"
down_revision: Union[str, None] = "0023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("apns_environment", ApnsEnvironment) in domain/models.py
# exactly (parity gate).
_ENV_CHECK_NEW = "apns_environment IN ('sandbox', 'production')"
# What 0023 left in the DB, restored by downgrade().
_ENV_CHECK_OLD = "push_environment IN ('sandbox', 'production')"


def upgrade() -> None:
    # Ordered deliberately: drop the CHECK that names the OLD column BEFORE the
    # rename, so the rebuild never emits a constraint referring to a column the
    # new table does not have; add the new CHECK after, against the new name.
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_push_environment", type_="check")
        batch_op.alter_column(
            "push_environment", new_column_name="apns_environment",
            existing_type=sa.String(length=16), existing_nullable=False,
            existing_server_default="production")
        batch_op.create_check_constraint(
            "ck_device_tokens_apns_environment", _ENV_CHECK_NEW)


def downgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_apns_environment", type_="check")
        batch_op.alter_column(
            "apns_environment", new_column_name="push_environment",
            existing_type=sa.String(length=16), existing_nullable=False,
            existing_server_default="production")
        batch_op.create_check_constraint(
            "ck_device_tokens_push_environment", _ENV_CHECK_OLD)
