"""device_tokens.push_environment -> apns_environment (#3386, Nick's ruling)

A name-only reconciliation to what #3386's body specified. Rationale for the
rename lives in the commit message; the naming argument lives on ApnsEnvironment
in domain/models.py. What is here is only what an operator cannot derive.

NOT A NO-OP ON THE ROWS. SQLite cannot rename a column a CHECK refers to, so batch
mode REBUILDS the table — create new, copy EVERY row, swap. Instantaneous at our
row counts; price it as a full table rewrite before running it against a big one.

THE WIRE FIELD MOVES WITH THE COLUMN — a BREAKING contract change, safe only
because there is no deployed consumer. MEASURED 2026-08-26, not a standing
invariant: aiko_chat_app's origin/main had zero references, its PR#162 was
unmerged, and the last submitted IPA carried no aps-environment entitlement. That
is why no dual-key window exists. Re-measure before trusting this.

DESYNC FAILS SILENTLY, so the order is fixed. The field is OPTIONAL: an unknown
key is ignored and the row takes the island default — so a stale app registers
with a 200, looks healthy, and every push to its token 400s where nobody sees it.
Island merges and DEPLOYS first, then aiko_chat_app#162.

FK-safety and the hand-written-not-autogenerated rule are unchanged from 0023 —
see that file. The CHECK literal below must stay in sync with ApnsEnvironment;
tests/test_migrations asserts it in the migrated DDL, and asserts a live row's
value survives 0023 -> 0024 rather than trusting the copy.

Revision ID: 0024
Revises: 0023
Create Date: 2026-08-26
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0024"
down_revision: Union[str, None] = "0023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("apns_environment", ApnsEnvironment) in domain/models.py
# exactly (parity gate).
_ENV_CHECK_NEW = "apns_environment IN ('sandbox', 'production')"
# What 0023 left in the DB, restored by downgrade().
_ENV_CHECK_OLD = "push_environment IN ('sandbox', 'production')"


def upgrade() -> None:
    # Ordered deliberately: drop the CHECK that names the OLD column BEFORE the
    # rename, so the rebuild never emits a constraint referring to a column the
    # new table does not have; add the new CHECK after, against the new name.
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_push_environment", type_="check")
        batch_op.alter_column(
            "push_environment", new_column_name="apns_environment",
            existing_type=sa.String(length=16), existing_nullable=False,
            existing_server_default="production")
        batch_op.create_check_constraint(
            "ck_device_tokens_apns_environment", _ENV_CHECK_NEW)


def downgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_apns_environment", type_="check")
        batch_op.alter_column(
            "apns_environment", new_column_name="push_environment",
            existing_type=sa.String(length=16), existing_nullable=False,
            existing_server_default="production")
        batch_op.create_check_constraint(
            "ck_device_tokens_push_environment", _ENV_CHECK_OLD)
