"""device_tokens.token_kind — what a push token is FOR (design 12 Decision 2)

`platform` records which transport FAMILY a token belongs to. It has never
recorded which DELIVERY SEMANTICS the token carries, because until now there was
only one: `apns.py` sent a hardcoded `apns-push-type: alert` and no VoIP path
existed at all. A CallKit ring needs a PushKit token against the `<bundle>.voip`
topic, which is a different string from a different registry, so the answer is a
property of the TOKEN and this column is where it lives.

NO BACKFILL, AND THAT IS THE INTERESTING PART. 0023 needed a settings-aware
UPDATE because its safe DDL default ('production') and the honest value for
pre-existing rows (whatever the box's APNS_USE_SANDBOX said) were different
questions with different answers. Here they are the same constant: the wire
contract is "absent means alert", and a row that predates this column is exactly
a row whose client never declared a kind. So `server_default='alert'` IS the
backfill — every existing row, every older client, and every direct SQL INSERT
that omits the column all get the value that was already true of them.

DEPLOY ORDER IS FIXED, AND DESYNC FAILS SILENTLY (the rule 0024 states, applying
again). `POST /v1/devices` ignores an unknown field, so an app shipping
`token_kind` against an island that has not deployed this gets a 201, the field
is DISCARDED, the row stores 'alert', and every subsequent VoIP push goes to a
token that is not a VoIP token — a 400 DeviceTokenNotForTopic, which is REJECTED,
which never reaps: no error anywhere and no ring. So: the island merges and
DEPLOYS FIRST, then `aiko_chat_app`. The 201 now echoes the resolved
`token_kind` precisely so the app can detect the mismatch.

SQLite cannot ALTER TABLE ... ADD CONSTRAINT, so batch_alter_table rebuilds the
table (create new + copy + swap). FK-safety: `device_tokens` is a CHILD only
(user_id -> users.id) and no table references it, so the swap cannot orphan a
dependant; and the gateway does not enable SQLite PRAGMA foreign_keys anyway —
it uses application-level explicit cascades (see accounts_service). Same note as
0002 / 0020 / 0022 / 0023.

HAND-WRITTEN, not autogenerated: alembic's compare_metadata is CHECK-blind on
SQLite (the deploy dialect), so --autogenerate emits no constraint. The literal
below must stay in sync with the TokenKind enum in domain/models.py;
tests/test_migrations asserts it structurally in the migrated DDL for that reason.

Revision ID: 0025
Revises: 0024
Create Date: 2026-09-09
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0025"
down_revision: Union[str, None] = "0024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("token_kind", TokenKind) in domain/models.py exactly
# (parity gate).
_KIND_CHECK = "token_kind IN ('alert', 'voip')"


def upgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("token_kind", sa.String(length=8), nullable=False,
                      server_default="alert"))
        batch_op.create_check_constraint(
            "ck_device_tokens_token_kind", _KIND_CHECK)


def downgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("ck_device_tokens_token_kind", type_="check")
        batch_op.drop_column("token_kind")
