"""device_tokens.install_id — which handset a token is on (claude-tasks#4384)

`token_kind` (0025) records what a token is FOR. Nothing records WHICH HANDSET it
is on, so an alert token and a VoIP token for one phone are two unrelated 64-hex
strings and "one push per handset" is not computable. The visible cost is a
CallKit ring with a redundant banner stacked behind it, seen on a real device on
2026-09-14. This column is the missing fact, minted by the client per app
INSTALL and sent with every registration.

NULLABLE, AND WITH NO server_default — the deliberate OPPOSITE of 0025, whose
whole note was that its server_default IS its backfill. That worked because
'absent means alert' was a TRUE statement about every pre-existing row. There is
no such constant here: any non-null value written into old rows would assert that
two tokens share a handset, and nothing established that. So NULL means UNKNOWN,
the router treats every unknown as its own handset, and pre-#4384 clients keep
their current behaviour exactly. There is no data migration to write, for the
opposite reason to 0025's.

NOT UNIQUE and NOT INDEXED. One install legitimately holds several rows — that is
the point — and the only reader groups rows already in memory for ONE user
(`push_service.plan_deliveries`), so there is no query to serve.

NO CHECK CONSTRAINT: `install_id` is an OPEN set, unlike every other constrained
column on this table. The only bound that exists is length and charset, and both
are enforced where the value enters (the REST model and the service door). A
CHECK could only restate the width, which SQLite does not enforce anyway.

DESYNC IS SAFE IN BOTH DIRECTIONS HERE, which is worth stating because 0024 and
0025 both had to warn the opposite. An app that sends `install_id` to an island
without this column gets a 201 and the field is discarded — the result is today's
behaviour, a redundant banner, not a silent non-delivery. And an island that has
this column but no client sending it is every row NULL, which is also today's
behaviour. The ordering rule still stands (island deploys first) but nothing
breaks if it is violated; the 201 echoes the stored value so the app can tell.

SQLite cannot ALTER TABLE ... ADD CONSTRAINT, so batch_alter_table rebuilds the
table (create new + copy + swap). FK-safety: `device_tokens` is a CHILD only
(user_id -> users.id) and no table references it, so the swap cannot orphan a
dependant; and the gateway does not enable SQLite PRAGMA foreign_keys anyway —
it uses application-level explicit cascades (see accounts_service). Same note as
0002 / 0020 / 0022 / 0023 / 0025.

HAND-WRITTEN, not autogenerated, per ISL-0001.

Revision ID: 0026
Revises: 0025
Create Date: 2026-09-15
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0026"
down_revision: Union[str, None] = "0025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# WIDTH: PICKED, NOT DERIVED — and it must equal the ORM's `String(64)`, which
# the migration parity test enforces. A UUID string is 36 characters and
# `identifierForVendor` renders as one; 64 leaves room for a client that prefixes
# or uses a longer opaque form without a second migration. Sized here rather than
# left magic for the same reason 0025's `_KIND_WIDTH` is a named constant: SQLite
# does not enforce VARCHAR width and Postgres does, so a width mismatch between
# the model and the migration is invisible on the platform we run.
_INSTALL_WIDTH = 64


def upgrade() -> None:
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("install_id", sa.String(length=_INSTALL_WIDTH),
                      nullable=True))


def downgrade() -> None:
    """A PLAIN DROP, and unlike 0025's refusal that is the correct answer here.

    0025 refuses to downgrade once any VoIP row exists because the column is the
    only durable distinction between two token kinds, and losing it routes an
    alert push to a VoIP token: a 400, never reaped, no ring. Losing `install_id`
    costs nothing of that shape. The router simply stops being able to group, so
    every row becomes its own handset again and arm (B) resumes — a redundant
    banner, which is a BLEMISH, and the exact state this island shipped in for
    the whole of v0.12.x. Nothing becomes undeliverable and no push is misrouted.

    The value itself is client-derivable: the next registration from any install
    restates it. So the drop is recoverable by the ordinary operation of the
    system, which is the property 0025 did not have.
    """
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_column("install_id")
