"""message_reports.reason — close the set (#7)

THE COLUMN WAS FOUND BY AN INSTRUMENT, NOT BY MEMORY, and that is the point of
the change it belongs to. `tests/test_closed_set_guard.py` is a structural
tripwire that introspects `Base.metadata` for every vocabulary-shaped string
column and requires each to carry an `x IN (...)` CHECK or an explicit waiver.
Its first run named exactly one unaccounted column: this one.

=== WHY IT WAS OPEN ===

The set was DECLARED — `moderation_service.REPORT_REASONS`, a bare tuple — but
enforced only at the HTTP boundary, where `rest/moderation.py` built a pydantic
enum from that tuple so an unknown reason is a 422. The service beneath it,
`report_message(reason: str)`, took a bare string and wrote it through. Measured
2026-09-26, service-layer write with a read-back from the DB:

    message_reports.reason persisted as: 'NOT_A_REASON'
    messages.sender_kind  refused:       IntegrityError   (positive control)

That is the single-door fallacy the v0.13.1 registration hole was — a gate on one
door rather than on the shared mutator (CLAUDE.md: "enforce at the backend,
through one door"). Note the asymmetry inside this one table: `resolution`, which
only ops writes, was enum'd and CHECK'd by Piece B; `reason`, which any user
writes over the wire, was not. The trusted writer got the gate.

=== SAFE AGAINST LIVE DATA — MEASURED, NOT ASSUMED ===

Read-only against both production DBs on 2026-09-26, before this file was written:

    chat.enspyr.co        message_reports: 0 rows
    chat.imagineering.cc  message_reports: 0 rows

So nothing out-of-set was ever stored, and the exposure was never an external
caller — the 422 held throughout. It was the SECOND caller: an in-process writer
such as the moderator agent (#19) or the takedown-forward path (#7), which is the
kind of caller this repo keeps growing.

Rows created between this measurement and the deploy are safe BY CONSTRUCTION,
not by luck: the only live writer is the route, and the route's pydantic enum
rejects everything outside the set. Re-run before deploying anyway, because a
zero is a fact about an instrument before it is a fact about the world:

    SELECT reason, count(*) FROM message_reports GROUP BY 1;

=== THE REPAIR ARM, WHICH 0027 DELIBERATELY DID NOT HAVE ===

0027 argued no repair arm was needed and was right to: it had no catch-all member
to fold into, and folding arbitrary values into 'unknown' would have asserted
something false about them. This set HAS a catch-all — `other` means precisely "a
reason outside the named ones" — so folding is honest here where it was not
there.

It matters because this repo is PUBLIC and meant to take outside operators
(CLAUDE.md, decided 2026-09-01). Neither island needs the arm; a stranger's
island with a hand-written row does, and without it their upgrade aborts MID
`batch_alter_table` rebuild — the wedged-boot failure ISL-0001 exists to prevent.
The fold IS lossy: the original string is gone. Accepted, because no supported
path could have produced it, and a loud abort on someone else's box is the worse
outcome. ORDER MATTERS for the same reason it did in 0027: the UPDATE must run
BEFORE create_check_constraint, or a surviving row fails the new constraint
during the copy.

=== MECHANICS ===

HAND-WRITTEN, not autogenerated: alembic's compare_metadata is CHECK-blind on
SQLite (the deploy dialect, ISL-0001), so --autogenerate emits no constraint. The
literal below must stay in sync with _in_check("reason", ReportReason) in
domain/models.py; tests/test_migrations asserts the constraint structurally and
tests/test_check_constraints makes the database refuse a bad value.

SQLite cannot ALTER TABLE ... ADD CONSTRAINT, so batch_alter_table rebuilds
`message_reports` (create new + copy + swap). The table is a CHILD of messages
and users and a parent of nothing; the gateway does not enable PRAGMA
foreign_keys and relies on application-level cascades (ISL-0002), so the swap
cannot trip an FK violation mid-rebuild. Same note as 0002, 0020, 0022 and 0027.

NO server_default, deliberately, for 0027's reason: the column already exists and
is already NOT NULL, and a default would invent a silent answer for a writer that
forgot to say why a message was reported.

Revision ID: 0028
Revises: 0027
Create Date: 2026-09-26
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0028"
down_revision: Union[str, None] = "0027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match _in_check("reason", ReportReason) in domain/models.py exactly
# (parity gate). Member ORDER follows the enum's declaration order, not alphabetical.
_REASON_CHECK = (
    "reason IN ('spam', 'harassment', 'hate', 'violence', 'sexual', 'other')")

# The catch-all member, and the only value the repair arm may write.
_CATCH_ALL = "other"


def upgrade() -> None:
    # BEFORE the constraint: a surviving out-of-set row would fail the new CHECK
    # during batch_alter_table's copy and abort the migration on a live box.
    # A no-op on both islands (0 rows, measured); the arm is for a third operator.
    op.execute(
        sa.text(
            "UPDATE message_reports SET reason = :catch_all "
            "WHERE reason NOT IN "
            "('spam', 'harassment', 'hate', 'violence', 'sexual', 'other')"
        ).bindparams(catch_all=_CATCH_ALL))
    with op.batch_alter_table("message_reports", schema=None) as batch_op:
        batch_op.create_check_constraint("ck_message_reports_reason", _REASON_CHECK)


def downgrade() -> None:
    # No data arm to reverse: the upgrade's fold is not restorable (the original
    # strings are gone), and every value that survives it is legal in the wider
    # pre-0028 column anyway. Dropping the constraint is the whole downgrade.
    with op.batch_alter_table("message_reports", schema=None) as batch_op:
        batch_op.drop_constraint("ck_message_reports_reason", type_="check")
