"""Bring the database to head — the container entrypoint runs this BEFORE uvicorn.

Why an explicit runner (not just `alembic upgrade head`): the gateway adopted
alembic AFTER a live DB already existed, built by the old ``create_all`` path.
That live DB has every table but no ``alembic_version`` row, so a naive
``upgrade head`` would run the baseline's ``CREATE TABLE users`` against a DB that
already has it and abort. The fix is **stamp-or-upgrade**:

  * fresh DB (no ``alembic_version``, no ``users``)      → ``upgrade head`` builds it
  * pre-alembic DB (``users`` present, no ``alembic_version``) → ``stamp 0001`` adopts
        the existing schema as the baseline, then ``upgrade head`` applies anything
        after it
  * already-managed DB (``alembic_version`` present)     → ``upgrade head`` only

The stamp target is ALWAYS the baseline (0001): the only pre-alembic database that
can ever exist is one built by ``create_all`` before this change shipped, and that
schema is, by construction, exactly revision 0001 (the baseline was autogenerated
from the same models). Later revisions are then applied by the trailing upgrade.

There is no host orchestrator to sequence "migrate before boot" (the deploy is a
manual ``docker compose up -d`` — see aiko_chat_gateway#19), so this MUST run in
the container entrypoint. It fails closed: any error propagates a non-zero exit
and the entrypoint never starts uvicorn on an unmigrated schema.
"""
from __future__ import annotations

import asyncio
import logging
import os

from alembic import command
from alembic.config import Config
from sqlalchemy import inspect
from sqlalchemy.ext.asyncio import create_async_engine

from .config import settings

log = logging.getLogger("aiko_gateway.migrate")

BASELINE_REVISION = "0001"


async def _existing_tables() -> set[str]:
    """Inspect over the app's async driver so no sync DB driver is needed (the
    deploy has only aiosqlite; dev has asyncpg). Short-lived NullPool engine."""
    engine = create_async_engine(settings.db_url, poolclass=None)
    try:
        async with engine.connect() as conn:
            return set(await conn.run_sync(lambda c: inspect(c).get_table_names()))
    finally:
        await engine.dispose()


def _alembic_config() -> Config:
    # Resolve alembic.ini relative to the repo/app root regardless of cwd: it
    # sits two levels up from this file (src/aiko_gateway/migrate.py -> root).
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    cfg = Config(os.path.join(root, "alembic.ini"))
    cfg.set_main_option("script_location", os.path.join(root, "alembic"))
    return cfg


def run() -> None:
    tables = asyncio.run(_existing_tables())
    cfg = _alembic_config()
    if "alembic_version" not in tables and "users" in tables:
        log.warning(
            "Adopting a pre-alembic database (tables present, no alembic_version)"
            " — stamping baseline %s before upgrade.", BASELINE_REVISION)
        command.stamp(cfg, BASELINE_REVISION)
    command.upgrade(cfg, "head")
    log.info("Database is at head.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
